# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ricca\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qarcconnect3\qarcconnect3_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QarcConnect3Dialog(object):
    def setupUi(self, QarcConnect3Dialog):
        QarcConnect3Dialog.setObjectName("QarcConnect3Dialog")
        QarcConnect3Dialog.resize(789, 312)
        self.buttonBox = QtWidgets.QDialogButtonBox(QarcConnect3Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(440, 280, 341, 32))
        # self.buttonBox.setOrientation(QtCore.Qt.Qt::Orientation::Horizontal)
        # self.buttonBox.setStandardButtons(QtCore.Qt.QDialogButtonBox::StandardButton::Cancel|QtCore.Qt.QDialogButtonBox::StandardButton::Ok)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok | QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(QarcConnect3Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 0, 751, 281))
        # self.tabWidget.setTabPosition(QtCore.Qt.QTabWidget::TabPosition::North)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        # self.tabWidget.setTabShape(QtCore.Qt.QTabWidget::TabShape::Rounded)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.loginButton = QtWidgets.QPushButton(self.tab)
        self.loginButton.setGeometry(QtCore.QRect(10, 230, 75, 24))
        self.loginButton.setObjectName("loginButton")
        self.UserSearchitemTableView = QtWidgets.QTableView(self.tab)
        self.UserSearchitemTableView.setGeometry(QtCore.QRect(10, 40, 731, 181))
        self.UserSearchitemTableView.setObjectName("UserSearchitemTableView")
        self.tabWidget.addTab(self.tab, "")
        self.agolContent = QtWidgets.QWidget()
        self.agolContent.setObjectName("agolContent")
        self.SearchitemTableView = QtWidgets.QTableView(self.agolContent)
        self.SearchitemTableView.setGeometry(QtCore.QRect(10, 40, 731, 181))
        self.SearchitemTableView.setObjectName("SearchitemTableView")
        self.SearchTextlineEdit = QtWidgets.QLineEdit(self.agolContent)
        self.SearchTextlineEdit.setGeometry(QtCore.QRect(10, 10, 281, 22))
        self.SearchTextlineEdit.setObjectName("SearchTextlineEdit")
        self.pushButtonSearch = QtWidgets.QPushButton(self.agolContent)
        self.pushButtonSearch.setGeometry(QtCore.QRect(310, 10, 75, 24))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.tabWidget.addTab(self.agolContent, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.gridLayout = QtWidgets.QGridLayout(self.settings)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.settings)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.saveCredsPushButton = QtWidgets.QPushButton(self.settings)
        self.saveCredsPushButton.setObjectName("saveCredsPushButton")
        self.gridLayout.addWidget(self.saveCredsPushButton, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.settings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.settings)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.settings)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.settings)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.settings)
        # self.passwordLineEdit.setEchoMode(QtCore.Qt.QLineEdit::EchoMode::Password)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.settings)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.settings)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout.addWidget(self.usernameLineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.settings)
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 5, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.settings)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.tabWidget.addTab(self.settings, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 741, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(QarcConnect3Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(QarcConnect3Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(QarcConnect3Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QarcConnect3Dialog)

    def retranslateUi(self, QarcConnect3Dialog):
        _translate = QtCore.QCoreApplication.translate
        QarcConnect3Dialog.setWindowTitle(_translate("QarcConnect3Dialog", "QGIS to ArcGIS Connector"))
        self.loginButton.setText(_translate("QarcConnect3Dialog", "Login"))
        # __sortingEnabled = self.itemListWidget.isSortingEnabled()
        # self.itemListWidget.setSortingEnabled(False)
        # item = self.itemListWidget.item(0)
        # item.setText(_translate("QarcConnect3Dialog", "New Item"))
        # self.itemListWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("QarcConnect3Dialog", "Own Content"))
        # __sortingEnabled = self.SearchitemListWidget.isSortingEnabled()
        # self.SearchitemListWidget.setSortingEnabled(False)
        # item = self.SearchitemListWidget.item(0)
        # item.setText(_translate("QarcConnect3Dialog", "New Item"))
        # self.SearchitemListWidget.setSortingEnabled(__sortingEnabled)
        self.pushButtonSearch.setText(_translate("QarcConnect3Dialog", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.agolContent), _translate("QarcConnect3Dialog", "AGOL Content"))
        self.lineEdit.setPlaceholderText(_translate("QarcConnect3Dialog", "10.192.168.1:80"))
        self.saveCredsPushButton.setText(_translate("QarcConnect3Dialog", "Save Settings"))
        self.label.setText(_translate("QarcConnect3Dialog", "Username"))
        self.pushButton.setText(_translate("QarcConnect3Dialog", "contact plugin owner"))
        self.label_3.setText(_translate("QarcConnect3Dialog", "https proxy"))
        self.label_4.setText(_translate("QarcConnect3Dialog", "Portal URL"))
        self.passwordLineEdit.setPlaceholderText(_translate("QarcConnect3Dialog", "password"))
        self.label_2.setText(_translate("QarcConnect3Dialog", "Password"))
        self.usernameLineEdit.setPlaceholderText(_translate("QarcConnect3Dialog", "user.name"))
        self.lineEdit_2.setPlaceholderText(_translate("QarcConnect3Dialog", "latest token is shown here"))
        self.pushButton_2.setText(_translate("QarcConnect3Dialog", "generate Token"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("QarcConnect3Dialog", "Settings"))
        self.textBrowser.setHtml(_translate("QarcConnect3Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><title>QarcConnector Help</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\" bgcolor=\"#fdfdfd\">\n"
"<h1 style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:xx-large; font-weight:700; color:#005a9c;\">QarcConnector – Plugin Help</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:xx-large; font-weight:700; color:#333333;\"> </span></h1>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#005a9c;\">🔗 Overview</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#333333;\"> </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-weight:700; color:#333333;\">QarcConnector</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\"> is a QGIS plugin that allows you to connect to private and public ArcGIS Online or ArcGIS Enterprise layers using token-based authentication. It supports both vector and feature layers and simplifies integration of Esri services into your QGIS projects. </span></p>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#005a9c;\">🔐 Authentication</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#333333;\"> </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\">QarcConnector uses Esri Token Authentication for secure access. The creentials are stored inside Qgis settings. The credentials are used to get a token and to access layers in QGIS. Every token is valid for 600min. If you want to work with secured items later on make sure to generate new tokens to the project and add it to an existing authentication configuration from </span><span style=\" font-family:\'Courier New\'; color:#333333;\">QGIS &gt; Settings &gt; Authentication</span></p>\n"
"<p style=\" margin-top:10px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffcc;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-weight:700; color:#333333;\">Note:</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\"> Esri tokens are usually short-lived. Make sure to renew them before expiry. </span></p>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#005a9c;\">🌐 Proxy Settings</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#333333;\"> </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\">If you\'re behind a corporate proxy, you can manually enter the proxy IP and port in the settings tab. These values will be stored in </span><span style=\" font-family:\'Courier New\'; color:#333333; background-color:#f2f2f2;\">QSettings</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\"> and automatically applied to all future requests made by the plugin. </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:5px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Leave the fields blank to disable proxy usage </li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">The proxy will be used for all <span style=\" font-family:\'Courier New\'; background-color:#f2f2f2;\">requests.get()</span> and <span style=\" font-family:\'Courier New\'; background-color:#f2f2f2;\">requests.post()</span> calls </li></ul>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#005a9c;\">📦 Supported Layers</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#333333;\"> </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\">You can connect to the following types of ArcGIS layers: </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:5px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">FeatureServer layers (vector features) </li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">MapServer layers (raster maps, when supported) </li></ul>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#005a9c;\">⚙️ Usage</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#333333;\"> </span></h2>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Open the QarcConnector panel</li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Enter user name and password in the Settings field</li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Optionally define a proxy</li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Click &quot;Save Settings&quot; to store everything for future use</li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Search</li>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\">- &quot;Own Content&quot;: list all your content</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\">- &quot;AGOL Content&quot;: search for items in AGOL</span></p>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Double click to access the service</li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">select the desired layer from the popup by double click</li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">layer will be added to th map</li></ol>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#005a9c;\">🛠️ Troubleshooting</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#333333;\"> </span></h2>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:5px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">If the layer does not appear, check that your token is still valid </li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Make sure the proxy settings (if used) are correct </li>\n"
"<li style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\">Check the QGIS Python console for error logs </li></ul>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#005a9c;\">📖 More Information</span><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; font-size:x-large; font-weight:700; color:#333333;\"> </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\">You can find Esri documentation on token authentication </span><a href=\"https://developers.arcgis.com/rest/users-groups-and-items/token.htm\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; text-decoration: underline; color:#003e92;\">here</span></a><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\">. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; color:#333333;\">For additional support / enhancement wishes or even integration in your corporate it contact the plugin owner: </span><a href=\"mailto:someone@example.com&amp;&amp;subject=Support QarcConnect\"><span style=\" font-family:\'Segoe UI\',\'sans-serif\'; text-decoration: underline; color:#003e92;\">Send email</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("QarcConnect3Dialog", "About / Readme"))
